permalink: /:year:month:day/:title
url: itsramisa.com
baseurl: /project

# variables
name: ramisa
description: hello this is a website
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
